In [1]:
##### Container sequences (heterogenous) : list, tuples, collections.deque : holds references
##### Flat sequences (homogenous) :  str, bytes, array.array : holds values


In [2]:
##### Mutable sequences : list, bytearray, array.array, collections.deque
##### Immutable sequences : tuple, str, bytes


In [3]:
from collections import abc

print (issubclass(abc.MutableSequence, abc.Sequence))
print (issubclass(abc.MutableSequence, abc.Collection))
print (issubclass(list, abc.MutableSequence))


True
True
True


In [4]:
symbols = '$¢£¥€¤'
codes = [ord(s) for s in symbols]
codes

[36, 162, 163, 165, 8364, 164]

In [5]:

codes = [l := ord(s) for s in symbols]
print (codes)
print (l)

[36, 162, 163, 165, 8364, 164]
164


In [6]:
print (list(filter (lambda s: s> 127, map(ord, symbols))))
print (list(ord(s) for s in symbols if ord(s) > 127))

[162, 163, 165, 8364, 164]
[162, 163, 165, 8364, 164]


In [7]:
## cartesian prod

colors = ['black', 'white']
sizes = ['S', 'M', 'L']

shirts = [(c, s) for c in colors for s in sizes]
shirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [8]:
## Generator expressions

symb = {ord(s) for s in symbols}
print (symb)

tups = tuple(ord(s) for s in symbols)
print (tups)

import array
arr = array.array('I', (ord(s) for s in symbols))
print (arr)

{162, 163, 36, 165, 164, 8364}
(36, 162, 163, 165, 8364, 164)
array('I', [36, 162, 163, 165, 8364, 164])


In [9]:
x = ('shiva', 'jobless', '33')
name, _, _ = x
print (name)

shiva


In [10]:
a = (10, 'alpha', [1,2])
b = a


print (a == b)

b[-1][0] = 8
print (a)
print (b)
print (a==b)

b[-1].append(9)

print (a==b)

print (a)
print (b)

True
(10, 'alpha', [8, 2])
(10, 'alpha', [8, 2])
True
True
(10, 'alpha', [8, 2, 9])
(10, 'alpha', [8, 2, 9])


In [11]:
try :
    hash(a)
except :
    print ("Cant hash a")
    
b = (1, 2)
hash(b)

Cant hash a


-3550055125485641917

In [12]:
mytup = (5, 4)
a, b = mytup
print (a, b)
b, a  = a, b
print (a, b)

a, b = divmod(20, 8)
print (f"{a}, {b}")


5 4
4 5
2, 4


In [13]:
import os

a, b = os.path.split("/usr/lib/crypto/libcrypto.so")

print (a, b)

/usr/lib/crypto libcrypto.so


In [14]:
a, b, *rest = range(10)

print (a, b)
print (rest)

a, b, c, *rest = range(3)
print (a, b, c, rest)

0 1
[2, 3, 4, 5, 6, 7, 8, 9]
0 1 2 []


In [15]:
def fun(a, b, c, d, *rest) :
    return a, b, c, d, rest

arr = [1, 2, 3]
fun(*arr, 10, 12, 13)

(1, 2, 3, 10, (12, 13))

In [16]:
1, 2, 3, 4, *range(4)


(1, 2, 3, 4, 0, 1, 2, 3)

In [17]:
def handle(msg) :
    match msg:
        case ['CREATE', data, arg] :
            print ("Create", data, arg)
        case ['READ', data] :
            print ("READ", data)
        case _ :
            print ("UNKNOWN", msg)
            
handle("Whatever")
handle(('CREATE',  18,  "foo"))
handle(("READ"))
handle(("READ", "Yo"))

UNKNOWN Whatever
Create 18 foo
UNKNOWN READ
READ Yo


In [18]:
## slicing
s = "bicycle"
print (s[::-1])
print (s[::2])
print (s[::-2])
print (s[::1])



elcycib
bcce
eccb
bicycle


In [19]:
invoice = """
0.....6.................................40........52...55........
1909    Pimoroni PiBrella                  $17.50     3    $52.50
1489    6mm Tactile Switch x20              $4.95     2     $9.90
1510    Panavise Jr. - PV-201              $28.00     1    $28.00
1601    PiTFT Mini Kit 320x240             $34.95     1    $34.95
"""

SKU = slice(0, 6)
DESC = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print (item[UNIT_PRICE], item[DESC], item[QUANTITY])

   $17.50      Pimoroni PiBrella                  3
    $4.95      6mm Tactile Switch x20             2
   $28.00      Panavise Jr. - PV-201              1
   $34.95      PiTFT Mini Kit 320x240             1
  


In [20]:
import numpy as np

a = np.arange(36).reshape(2, 6, 3)
print (a)
print (a[..., 1:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]
  [10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]
  [28 29]
  [31 32]
  [34 35]]]


In [21]:
l = [1, 2, 3]
l*5
'abcd' * 5

'abcdabcdabcdabcdabcd'

In [22]:
l = ['_']*3
l[0] = 8
print (l)


[8, '_', '_']


In [23]:
l = [[_]*2] * 2
print (l)
l[0][1] = 8
print (l)

l = [['_'] * 3 for i in range(3)]
print (l)
l[0][1] = 9
print (l)

[['33', '33'], ['33', '33']]
[['33', 8], ['33', 8]]
[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', 9, '_'], ['_', '_', '_'], ['_', '_', '_']]


In [24]:
l = [1, 2, 3]
print (id(l))
l *= 2
print (l)
print (id(l))

t = (1, 2, 3)
print (id(t))
t *= 2
print (t)
print (id(t))

4604999680
[1, 2, 3, 1, 2, 3]
4604999680
4603940928
(1, 2, 3, 1, 2, 3)
4577748992


In [27]:
t = (1, 2, [30, 40])
try :
    t[2] += [50, 60]
except :
    print ("error")

print (t)

error
(1, 2, [30, 40, 50, 60])


In [32]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

print (floats.typecode)

d


In [37]:
from collections import deque

dq = deque(range(10), maxlen=10)
dq.rotate(-2)
print(dq)

deque([2, 3, 4, 5, 6, 7, 8, 9, 0, 1], maxlen=10)
